HW1: 22003191_Aksakal_FurkanMert_hw1.o sorting.o
	g++ 22003191_Aksakal_FurkanMert_hw1.o sorting.o -o hw1

22003191_Aksakal_FurkanMert_hw1.o: 22003191_Aksakal_FurkanMert_hw1.cpp
	g++ -c 22003191_Aksakal_FurkanMert_hw1.cpp

sorting.o: sorting.cpp sorting.h
	g++ -c sorting.cpp

