HW2 : main.o BST.o BSTNode.o analysis.o
	g++ main.o BST.o BSTNode.o analysis.o -o HW2

BST.o : BST.cpp
	g++ -c BST.cpp

BSTNode.o : BSTNode.cpp
	g++ -c BSTNode.cpp

analysis.o: analysis.cpp
	g++ -c analysis.cpp

main.o : main.cpp
	g++ -c main.cpp